name: Lint

on: [pull_request, push]

jobs:
  job:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint
      uses: github/super-linter@v3
      env:
        FILTER_REGEX_EXCLUDE: CODE_OF_CONDUCT\.md
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_MARKDOWN: true
        VALIDATE_YAML: true
